config/routes.rb
Rails.application.routes.draw do
  resources :pickup_lines
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  namespace :rizzler do
    resource :demo, only: [:show, :create], controller: :demo
    resource :chat, only: [:show, :create], controller: :chat do
      scope module: :chat do
        resources :answers
      end
    end
    resource :rescue, only: [:show], controller: :rescue
  end
  resource :rizzler, only: [:show], controller: :rizzler
  # Defines the root path route ("/")
  authenticated :user do
    root to: 'rizzler#show', as: :authenticated_user_root
  end

  unauthenticated :user do
    root to: "pages#home", as: :unauthenticated_user_root
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pickup_line.rb
class PickupLine < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pickup_lines_controller.rb
class PickupLinesController < ApplicationController
  before_action :set_pickup_line, only: %i[ show edit update destroy ]

  # GET /pickup_lines or /pickup_lines.json
  def index
    @pickup_lines = PickupLine.all
  end

  # GET /pickup_lines/1 or /pickup_lines/1.json
  def show
  end

  # GET /pickup_lines/new
  def new
    @pickup_line = PickupLine.new
  end

  # GET /pickup_lines/1/edit
  def edit
  end

  # POST /pickup_lines or /pickup_lines.json
  def create
    @pickup_line = PickupLine.new(pickup_line_params)
    @pickup_line.user = current_user
    respond_to do |format|
      if @pickup_line.save
        format.html { redirect_to pickup_line_url(@pickup_line), notice: "Pickup line was successfully created." }
        format.json { render :show, status: :created, location: @pickup_line }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pickup_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pickup_lines/1 or /pickup_lines/1.json
  def update
    respond_to do |format|
      if @pickup_line.update(pickup_line_params)
        format.html { redirect_to pickup_line_url(@pickup_line), notice: "Pickup line was successfully updated." }
        format.json { render :show, status: :ok, location: @pickup_line }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pickup_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pickup_lines/1 or /pickup_lines/1.json
  def destroy
    @pickup_line.destroy!

    respond_to do |format|
      format.html { redirect_to pickup_lines_url, notice: "Pickup line was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pickup_line
      @pickup_line = PickupLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pickup_line_params
      params.require(:pickup_line).permit(:text)
    end
end

app/controllers/rizzler/chat/answers_controller.rb
module Rizzler
  module Chat
    class AnswersController < ApplicationController
      def create
        # // GIVE W RIZZ ADVICE
        question = "Give me dating advice to make a girl attracted to me "
        question += params[:text]
        @answer = Answer.create(question: question)
        @answer.broadcast_replace_to(current_user, target: "logo", partial: "rizzler/chat/loading")
        @answer.broadcast_update_to(current_user, target: "form", partial: "rizzler/chat/form")
        client = OpenAI::Client.new
        response = client.chat(
          parameters: { 
              model: "gpt-3.5-turbo", # Required.
              messages: [{ role: "user", content: question }], # Required.
              temperature: 0.7,
          })
        Answer.update(response: response['choices'][0]['message']['content'])
        redirect_to rizzler_chat_answers_path(answer_id: @answer.id)
      end

      def index
        @answer = Answer.find(params[:answer_id])
      end
    end
  end
end

app/controllers/rizzler/chat_controller.rb
module Rizzler
  class ChatController < ApplicationController
    def show; end

    def create; end
  end
end

app/controllers/rizzler/demo_controller.rb
module Rizzler
  class DemoController < ApplicationController
    def show;end
  end
end

app/controllers/rizzler/rescue_controller.rb
module Rizzler
  class RescueController < ApplicationController
    def show
    end
  end
end

app/controllers/rizzler_controller.rb
class RizzlerController < ApplicationController
  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pickup_lines_helper.rb
module PickupLinesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<div class="w-full h-16 bg-gray-800 flex items-center justify-between px-8"> 
  <%= link_to "/", class: "text-gray-100 text-2xl" do %>
    <div class="flex items-center gap-2">
      <span>The Rizzler</span>
      <%= image_tag "charm.png", class: "h-10 invert" %>
    </div>
  <% end %>
  <div class="flex">
    <%= link_to "Sign out", destroy_user_session_path, class: "bg-gray-600 text-gray-100 p-2 rounded-lg", data: { turbo_method: :delete } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rizzler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" if current_user %>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-gradient-to-b from-indigo-500 via-indigo-400 to-pink-500 min-h-[150vh] flex flex-col items-center gap-2 pt-32">
  <h1 class="font-bold text-7xl text-indigo-100">Rizzler</h1>
  <p class="text-2xl text-indigo-200 max-w-lg text-center"> Get anyone to fall in love with you <br/> with The Rizzler as you're wingman</p>

  <div class="flex gap-4">
    <%= link_to "Log in", new_user_session_path, class: "bg-green-500 text-green-100 p-2 rounded-lg hover:bg-green-700" %>
    <%= link_to "Try it out now", rizzler_demo_path, class: "bg-indigo-600 text-indigo-100 py-2 px-4 rounded-full hover:bg-indigo-700" %>
  </div>
</div>

app/views/pickup_lines/_form.html.erb
<%= form_with(model: pickup_line, class: "contents") do |form| %>
  <% if pickup_line.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(pickup_line.errors.count, "error") %> prohibited this pickup_line from being saved:</h2>

      <ul>
        <% pickup_line.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :text %>
    <%= form.text_area :text, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pickup_lines/_pickup_line.html.erb
<div id="<%= dom_id pickup_line %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Text:</strong>
    <%= pickup_line.text %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Posted by</strong>
     <%= pickup_line.user.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this pickup line", pickup_line, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this pickup line", edit_pickup_line_path(pickup_line), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/pickup_lines/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pickup line</h1>

  <%= render "form", pickup_line: @pickup_line %>

  <%= link_to "Show this pickup line", @pickup_line, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pickup lines", pickup_lines_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pickup_lines/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pickup lines</h1>
    <%= link_to "New pickup line", new_pickup_line_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="pickup_lines" class="min-w-full">
    <%= render @pickup_lines %>
  </div>
</div>

app/views/pickup_lines/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pickup line</h1>

  <%= render "form", pickup_line: @pickup_line %>

  <%= link_to "Back to pickup lines", pickup_lines_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pickup_lines/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pickup_line %>

    <%= link_to "Edit this pickup_line", edit_pickup_line_path(@pickup_line), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this pickup_line", pickup_line_path(@pickup_line), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to pickup_lines", pickup_lines_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/rizzler/chat/_form.html.erb
<%= form_with url: rizzler_chat_answers_path, data: { turbo_frame: "chat" } do |f| %>
  <%= f.text_area :text, class: "block w-full bg-gray-500 text-gray-100", style: "resize: none;", data: { controller: "auto-adjust", action: "auto-adjust#adjust" },
      placeholder: "Enter your questions here" %>
  <br/>
  <%= f.submit "Ask Rizzler", class: "bg-indigo-500 text-indigo-100 p-3 rounded-lg cursor-pointer" %>
<% end %>

app/views/rizzler/chat/_loading.html.erb
<p class="text-lg text-indigo-100"> Loading... </p>

<iframe src="https://giphy.com/embed/hatz3YjuDO0BG" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/hatz3YjuDO0BG">via GIPHY</a></p>

app/views/rizzler/chat/answers/index.html.erb
<%= turbo_frame_tag :chat do %>
  <p class="text-2xl text-gray-100"> <%= @answer.response %> </p>
<% end %>

app/views/rizzler/chat/show.html.erb
<%= turbo_stream_from current_user %>

<div class="bg-gradient-to-b from-indigo-500 via-indigo-400 to-pink-500 min-h-[150vh] flex flex-col items-center pt-16 px-6 md:px-0">
  <div class="w-full max-w-5xl rounded-lg min-h-[70vh]">
    <div class="w-full flex items-center justify-center p-8">
      <%= turbo_frame_tag :chat do %>
        <div class="flex flex-col items-center" id="logo">
          <%= image_tag "charm.png", class: "h-56 fill-indigo-900" %>
          <h2 class="text-2xl text-indigo-100"> Ask me anything and ill try my best to help </h2>
        </div>
      <% end %>
    </div>
    <div class="max-w-lg w-full mx-auto p-4 bg-indigo-100" id="form">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/rizzler/demo/show.html.erb
<div class="bg-gradient-to-b from-indigo-500 via-indigo-400 to-pink-500 min-h-[150vh] flex flex-col items-center gap-2 pt-32">
  <h1 class="text-5xl text-indigo-100 text-center"> Try out The Rizzler </h1>
</div>

app/views/rizzler/rescue/show.html.erb
<%= turbo_stream_from current_user %>

<div class="bg-gradient-to-b from-indigo-500 via-indigo-400 to-pink-500 min-h-[150vh] flex flex-col items-center gap-2 pt-32">
  <h1 class="text-3xl text-gray-100"> Lets get you out of this sticky sich </h1>
  <div class="w-full max-w-5xl rounded-lg min-h-[70vh]">
    <div class="w-full flex items-center justify-center p-8">
      <%= turbo_frame_tag :chat do %>
        <div class="flex flex-col items-center" id="logo">
          <%= image_tag "rescue.png", class: "h-56 fill-indigo-900" %>
          <h2 class="text-2xl text-indigo-100"> Ask me anything and ill try my best to help </h2>
        </div>
      <% end %>
    </div>
    <div class="max-w-lg w-full mx-auto p-4 bg-indigo-100" id="form">
      <%= render "rizzler/chat/form" %>
    </div>
  </div>
</div>

app/views/rizzler/show.html.erb
<div class="bg-gradient-to-b from-indigo-500 via-indigo-400 to-pink-500 min-h-[150vh] flex flex-col items-center gap-2 pt-32">
  <%= image_tag "charm.png", class: "h-56 fill-indigo-900" %>
  <h1 class="text-6xl text-indigo-100 text-center"> The Rizzler </h1>

  <h2 class="text-2xl text-gray-100 mt-20 border-b border-gray-100"> How can I assist you?</h2>
  <div class="grid grid-cols-4 gap-8 w-full max-w-5xl mt-6">
    <a href="<%= rizzler_chat_path %>" class="w-full bg-indigo-500 hover:bg-indigo-600 rounded-lg text-indigo-100 h-56 text-3xl flex items-center justify-center text-center transition duration-250"> 
      Assist with a date
    </a>

    <a href="<%= pickup_lines_path %>" class="w-full bg-indigo-500 hover:bg-indigo-600 rounded-lg text-indigo-100 h-56 text-3xl flex items-center justify-center text-center transition duration-250"> 
      Pick up lines
    </a>

    <a href="<%= rizzler_rescue_path %>" class="w-full bg-indigo-500 hover:bg-indigo-600 rounded-lg text-indigo-100 h-56 text-3xl flex items-center justify-center text-center transition duration-250"> 
      Uno Reverse
    </a>
  </div>
</div>